$ANSIBLE_VAULT;1.1;AES256
35386263393761303238323632316630356438626532613736306463343236623635653263626536
6638306234376239356363333064343561306161616139630a373335653263613066373037656533
33623766313835333265366361663264653062383930613865333465636162343763386334616238
6337663662646230650a666434326362323265306335643534613434623031383365656531353939
37376639626164656339376532653366376634633130373333393663323763363638326130326463
63353232313865303138653330386461343761656161646632393235386333613131626232636261
66323261646136623562636436323139643332383966366561333339346532393765396265333338
32333764343062373331363335373035306461666138333465336239623039663862666363333830
36353839653833333031666437633837666330646332316630616362376234656464396461663766
62376432653530356262373232303738393236333664373462663137623735306561346465383966
39646363613737656664383130613132396135353433323465343363303237353136363063653562
32623032346334633536326538386138356566666364323530353438626365306130623865643630
36633135333437326136313661306638663861376433313962663564336161373439333265323265
38646431636635313066356634333336613266313262376264346666383834623635353034333961
62336435626266336531346630626663316264633432323536613466323131666231323661326335
34316337326661396562373261306235376365626433343966313333623430386663386464386139
3438
